### ISSUE TITLE
Great tutorial

### ISSUE THREAD

**Issue by tied** [comsysto/kitchen-duty-plugin-for-atlassian-jira#2]
Can't await the next steps :) 

Looks like a really good JIRA plugin example, which will cover most parts of a plugin and how to put all together into a example which helps people (like me) who are not so familiar with plugin development to see how all works together.

**Comment by csgruenebe** [comment]
Thank's for your early feedback :)

I will try to update it soon to at least finish the Admin Page completely (which will anyway be the biggest part). I think you can just watch the repository and be then informed if I commit something :)

**Comment by csgruenebe** [comment]
hi @tied 

I just finished [step 04](https://comsysto.github.io/kitchen-duty-plugin-for-atlassian-jira/tutorial/07-step-04-planning-page--kitchen-duty-planning-rest-resource/)

And I will update the [news page](https://comsysto.github.io/kitchen-duty-plugin-for-atlassian-jira/news/) from now own so you can stay informed.

Hope you enjoy the new content :)
