### ISSUE TITLE
Unable to sucessfully run stage one

### ISSUE THREAD

**Issue by Jimb161** [comsysto/kitchen-duty-plugin-for-atlassian-jira#3]
Hi

I get the following error when trying to run stage one of your tutorial

[INFO] [talledLocalContainer] 2016-11-30 20:57:46,051 http-nio-2990-exec-8 ERROR admin 1257x808x1 mxwdbv 0:0:0:0:0:0:0:1 /se
cure/KitchenDutyPlanningWebworkAction.jspa [c.a.j.web.dispatcher.JiraWebworkActionDispatcher] Exception thrown from action '
KitchenDutyPlanningWebworkAction', returning 404
[INFO] [talledLocalContainer] WebworkConfigurationNotFoundException{class=class webwork.config.XMLActionConfiguration, messa
ge='No such view mapping', name='KitchenDutyPlanningWebworkAction.actionRoles.actionRoles'}

I have compared your files with those I generated and can find no difference in content.

Please advise

Thanks
Jim

**Comment by clouless** [comment]
Hi,

You need to look for the error yourself. That is 80% of Plugin development. As the error suggests
```
'No such view mapping', name='KitchenDutyPlanningWebworkAction.actionRoles.actionRoles'}
````

So somewhere you want to call a view name `actionRoles` and have not valid view file.

When I run `step-01` with `atlas-run` I have no errors.

So check `atlas-plugin.xml` and your templates.

I cannot give any further support. It is best to ask the community at https://answers.atlassian.com/questions/topics/753669/jira for further support.

good luck,

bg
