### ISSUE TITLE
Is this demo project going further or is is dead?

### ISSUE THREAD

**Issue by dgg23** [comsysto/kitchen-duty-plugin-for-atlassian-jira#4]

**Comment by csgruenebe** [comment]
it will continue maybe next year. It is a lot of work that happens in my free time so it will continue but not very fast.

**Comment by dgg23** [comment]
OK thanks

**Comment by csgruenebe** [comment]
thanks.

I will continue once Atlassian has officially released the new ReactJS based UI Kit.
They are planning to rollout this year.

**Comment by tweinreich** [comment]
Thank you for the quick response. I'm looking forward to it :-)
