### ISSUE TITLE
jira-plugin resoure

### ISSUE THREAD

**Issue by chenjiaobin** [comsysto/kitchen-duty-plugin-for-atlassian-jira#6]
hellow，I'm develop jira-plugin,but I don't how to remove jira's default style. now i want to use myself header and sidebar.could you please tell me how to do it . Thanks
@bojzi @tlercher @forgemo @rpelger @dkokic 
![default](https://user-images.githubusercontent.com/24197503/32715344-e50587fe-c88c-11e7-9cd3-2324d0695416.png)

**Comment by clouless** [comment]
At best ask at https://community.atlassian.com/ there are a lot of people who can answer.
We do not answer questions of that kind here.
