### ISSUE TITLE
Great Tutorial

### ISSUE THREAD

**Issue by ahmedatinfosysta** [comsysto/kitchen-duty-plugin-for-atlassian-jira#7]
Thank you very much for this great tutorial, I have two questions:
1 - Is there any tutorial for JIRA development, like your excellent one.
2 - When you will finish the remaining steps.

Thank you

**Comment by clouless** [comment]
Hi, good to hear that you like it.
Unfortunately I currently do not have the time to continue it :(
Also I want to wait what happens with Redesign of JIRA and if the AUI is fully replaced by ReactJS stuff.
But it is on my todolist and I will continue it some day :)

I didn't find any other good tutorials and was just experimenting around much and googling stuff.
I hope the Server-Team of atlassian will provide some good tutorials in the future :)
A lot of questions are already answered on https://community.atlassian.com/
